[package]
name = "nodeJsWebSocket"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13"
actix-web = "4.4"
actix-web-actors = "4.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.6", features = ["v4"] }
